# Generated by Django 3.2.16 on 2025-05-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='birthday',
            new_name='post',
        ),
    ]
